data:
  input_path: '/data/full_dataset.csv'
  output_path: '/data/processed/experiment_1'
  use_dimension_reduction: True
  reduction_method: 'PCA' # random or selecting highly variable features
  sample_size: 10000  # Number of rows to use
  feature_size: 20000  # Number of columns to use
  seed: 42

training:
  model_type: 'vae'
  hidden_dims: [10000, 5000, 2048]
  latent_dim: 1024
  batch_size: 16
  dropout_rate: 0.2
  learning_rate: 1e-6
  epochs: 20
  seed: 42
