data:
  input_path: ''
  output_path: 'data/processed/experiment_random'
  use_dimension_reduction: False
  sample_size: 10000  # Number of rows to use
  feature_size: 20000  # Number of columns to use
  seed: 42

# training:
#   model_type: 'vae'
#   hidden_dims: [10000, 5000, 2048]
#   latent_dim: 1024
#   batch_size: 16
#   dropout_rate: 0.2
#   learning_rate: 1e-6
#   epochs: 20
#   seed: 42
