set_seed: 42

random_data:
  rows: 10000          # Number of rows in the generated matrix
  cols: 20000          # Number of columns (features) in the generated matrix
  mean: 0              # Mean of the Gaussian distribution
  variance: 1          # Variance of the Gaussian distribution
  output_dir: 'data/random_data_zero/'  # Output directory to save the random matrix and labels
  matrix_name: 'random_matrix_10000_20000.pkl'  # matrix name to save the random matrix
  labels_name: 'random_labels_10000_20000.pkl'  # labels name to save the random labels
  regenerate: False            # If True, regenerate the random matrix
  zero_cols: 19000          # Number of zeros features to mak in the random matrix

random_train_test_split:
  input_path: 'data/random_data_zero/'
  matrix_name: 'random_matrix_10000_20000.pkl'
  labels_name: 'random_labels_10000_20000.pkl'
  output_dir: 'data/random_data_zero/split_data'
  test_size: 0.3
  val_size: 0.4
  regenerate: False            # If True, regenerate the random matrix

training_vae:
  model_type: 'vae'
  input_dir: 'data/random_data_zero/split_data'
  output_dir: 'experiments/random_data_zero_vae'
  checkpoint_monitor: 'val_loss'
  checkpoint_mode: 'min'
  hidden_dims: [10000, 5000, 2048]
  latent_dim: 1024
  batch_size: 16
  dropout_rate: 0.0
  learning_rate: 0.000001
  max_epochs: 20
  kl_weight: 5.0
  seed: 42

# loading_vae:
#   model_type: 'vae'
#   checkpoint_path: 'experiments/random_data_vae/checkpoints/best_model.h5'
#   hparams_path: 'experiments/random_data_vae/hparams.yaml'
#   input_dir: 'experiments/random_data_vae'
#   output_dir: 'experiments/random_data_vae'
#   checkpoint_monitor: 'val_loss'
#   checkpoint_mode: 'min'
#   seed: 42
